name: Dart

on:
  push:
    branches: [ "account" ]
  pull_request:
    branches: [ "account" ]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11.0.16.1'
          distribution: 'adopt'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.7.12'
      - name: Install Flutter dependencies
        run: flutter pub get
      - name: Run Flutter unit tests
        run: flutter test
